-- BoardBuddies Supabase schema (privacy-safe version)
-- Based on your provided SQL, adapted for:
-- 1) OAuth-first signup
-- 2) Email/password login after signup
-- 3) No raw Thai ID card number storage

DO $$ BEGIN
  CREATE TYPE join_status AS ENUM ('pending', 'accepted', 'rejected');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.users (
  uid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_id UUID UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  name VARCHAR(30) NOT NULL,
  surname VARCHAR(30) NOT NULL,
  username VARCHAR(30) UNIQUE,
  google_auth_id VARCHAR(255) UNIQUE,
  thai_citizen_id_hash TEXT NOT NULL,
  thai_citizen_id_last4 VARCHAR(4) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.members (
  vid BIGINT PRIMARY KEY REFERENCES public.users(uid) ON DELETE CASCADE,
  subscription_date TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.parties (
  pid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  party_name VARCHAR(50) NOT NULL,
  location_data JSONB,
  host_id BIGINT REFERENCES public.users(uid),
  appointment_time TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.party_joins (
  party_id BIGINT REFERENCES public.parties(pid) ON DELETE CASCADE,
  user_id BIGINT REFERENCES public.users(uid) ON DELETE CASCADE,
  request_time TIMESTAMPTZ DEFAULT NOW(),
  status join_status DEFAULT 'pending',
  checked_in_at TIMESTAMPTZ,
  confirmed_arrival BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (party_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.board_game_catalogue (
  catalogue_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.physical_board_games (
  item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  catalogue_id BIGINT REFERENCES public.board_game_catalogue(catalogue_id),
  borrower_id BIGINT REFERENCES public.members(vid),
  status VARCHAR(20) DEFAULT 'available',
  last_updated TIMESTAMPTZ DEFAULT NOW()
);

CREATE OR REPLACE VIEW public.user_reliability_stats AS
SELECT
  user_id,
  COUNT(*) AS total_parties_accepted,
  COUNT(*) FILTER (WHERE confirmed_arrival = TRUE) AS actual_arrivals,
  ROUND(
    (
      COUNT(*) FILTER (WHERE confirmed_arrival = TRUE)::numeric /
      NULLIF(COUNT(*), 0)
    ) * 100,
    2
  ) AS reliability_score
FROM public.party_joins
WHERE status = 'accepted'
GROUP BY user_id;

CREATE INDEX IF NOT EXISTS idx_users_auth_id ON public.users(auth_id);
CREATE INDEX IF NOT EXISTS idx_parties_host_id ON public.parties(host_id);
CREATE INDEX IF NOT EXISTS idx_party_joins_user_id ON public.party_joins(user_id);

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.parties ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.party_joins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.board_game_catalogue ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.physical_board_games ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "users_select_own_profile" ON public.users;
CREATE POLICY "users_select_own_profile"
ON public.users
FOR SELECT
USING (auth.uid() = auth_id);

DROP POLICY IF EXISTS "users_insert_own_profile" ON public.users;
CREATE POLICY "users_insert_own_profile"
ON public.users
FOR INSERT
WITH CHECK (auth.uid() = auth_id);

DROP POLICY IF EXISTS "users_update_own_profile" ON public.users;
CREATE POLICY "users_update_own_profile"
ON public.users
FOR UPDATE
USING (auth.uid() = auth_id);

DROP POLICY IF EXISTS "members_select_own" ON public.members;
CREATE POLICY "members_select_own"
ON public.members
FOR SELECT
USING (
  vid IN (SELECT uid FROM public.users WHERE auth_id = auth.uid())
);

DROP POLICY IF EXISTS "members_insert_own" ON public.members;
CREATE POLICY "members_insert_own"
ON public.members
FOR INSERT
WITH CHECK (
  vid IN (SELECT uid FROM public.users WHERE auth_id = auth.uid())
);

DROP POLICY IF EXISTS "parties_public_read" ON public.parties;
CREATE POLICY "parties_public_read"
ON public.parties
FOR SELECT
USING (TRUE);

DROP POLICY IF EXISTS "parties_insert_owner" ON public.parties;
CREATE POLICY "parties_insert_owner"
ON public.parties
FOR INSERT
WITH CHECK (
  host_id IN (SELECT uid FROM public.users WHERE auth_id = auth.uid())
);

DROP POLICY IF EXISTS "parties_update_owner" ON public.parties;
CREATE POLICY "parties_update_owner"
ON public.parties
FOR UPDATE
USING (
  host_id IN (SELECT uid FROM public.users WHERE auth_id = auth.uid())
);

DROP POLICY IF EXISTS "parties_delete_owner" ON public.parties;
CREATE POLICY "parties_delete_owner"
ON public.parties
FOR DELETE
USING (
  host_id IN (SELECT uid FROM public.users WHERE auth_id = auth.uid())
);

DROP POLICY IF EXISTS "party_joins_public_read" ON public.party_joins;
CREATE POLICY "party_joins_public_read"
ON public.party_joins
FOR SELECT
USING (TRUE);

DROP POLICY IF EXISTS "party_joins_insert_self" ON public.party_joins;
CREATE POLICY "party_joins_insert_self"
ON public.party_joins
FOR INSERT
WITH CHECK (
  user_id IN (SELECT uid FROM public.users WHERE auth_id = auth.uid())
);

DROP POLICY IF EXISTS "party_joins_update_self_or_host" ON public.party_joins;
CREATE POLICY "party_joins_update_self_or_host"
ON public.party_joins
FOR UPDATE
USING (
  user_id IN (SELECT uid FROM public.users WHERE auth_id = auth.uid())
  OR party_id IN (
    SELECT pid
    FROM public.parties
    WHERE host_id IN (SELECT uid FROM public.users WHERE auth_id = auth.uid())
  )
);

DROP POLICY IF EXISTS "catalogue_public_read" ON public.board_game_catalogue;
CREATE POLICY "catalogue_public_read"
ON public.board_game_catalogue
FOR SELECT
USING (TRUE);

DROP POLICY IF EXISTS "physical_games_member_read" ON public.physical_board_games;
CREATE POLICY "physical_games_member_read"
ON public.physical_board_games
FOR SELECT
USING (TRUE);
