-- Party chat support (demo-friendly, RLS-safe)
-- Adds a shared chat timeline for host + pending/accepted participants.

CREATE TABLE IF NOT EXISTS public.party_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  party_id BIGINT NOT NULL REFERENCES public.parties(pid) ON DELETE CASCADE,
  sender_id BIGINT NOT NULL REFERENCES public.users(uid) ON DELETE CASCADE,
  sender_name VARCHAR(60) NOT NULL DEFAULT 'Player',
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT party_messages_message_not_empty CHECK (char_length(trim(message)) > 0),
  CONSTRAINT party_messages_message_max_len CHECK (char_length(message) <= 500)
);

ALTER TABLE public.party_messages
ADD COLUMN IF NOT EXISTS sender_name VARCHAR(60) NOT NULL DEFAULT 'Player';

UPDATE public.party_messages pm
SET sender_name = COALESCE(NULLIF(TRIM(u.username), ''), CONCAT(u.name, ' ', u.surname), 'Player')
FROM public.users u
WHERE u.uid = pm.sender_id
  AND (pm.sender_name IS NULL OR TRIM(pm.sender_name) = '');

CREATE INDEX IF NOT EXISTS idx_party_messages_party_id_created_at
ON public.party_messages (party_id, created_at);

ALTER TABLE public.party_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "party_messages_select_participants" ON public.party_messages;
CREATE POLICY "party_messages_select_participants"
ON public.party_messages
FOR SELECT
USING (
  EXISTS (
    SELECT 1
    FROM public.parties p
    JOIN public.users u ON u.uid = p.host_id
    WHERE p.pid = public.party_messages.party_id
      AND u.auth_id = auth.uid()
  )
  OR EXISTS (
    SELECT 1
    FROM public.party_joins j
    JOIN public.users u ON u.uid = j.user_id
    WHERE j.party_id = public.party_messages.party_id
      AND j.status IN ('pending', 'accepted')
      AND u.auth_id = auth.uid()
  )
);

DROP POLICY IF EXISTS "party_messages_insert_participants" ON public.party_messages;
CREATE POLICY "party_messages_insert_participants"
ON public.party_messages
FOR INSERT
WITH CHECK (
  sender_id IN (
    SELECT uid
    FROM public.users
    WHERE auth_id = auth.uid()
  )
  AND (
    EXISTS (
      SELECT 1
      FROM public.parties p
      WHERE p.pid = public.party_messages.party_id
        AND p.host_id = public.party_messages.sender_id
    )
    OR EXISTS (
      SELECT 1
      FROM public.party_joins j
      WHERE j.party_id = public.party_messages.party_id
        AND j.user_id = public.party_messages.sender_id
        AND j.status IN ('pending', 'accepted')
    )
  )
);
